name: CI

on:
  pull_request:
    branches:
      - master
      - develop

jobs:
  ci-build:
    runs-on: ubuntu-latest
    env:
      working-directory: ./proto-app

    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-node@v1

      - name: Installation â³
        run: yarn install
        working-directory: ${{env.working-directory}}

      - name: Test ğŸ§ª
        run: yarn test
        working-directory: ${{env.working-directory}}

      - name: Build ğŸ§±
        run: yarn build-ghpages
        working-directory: ${{env.working-directory}}
